/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as IbRouteImport } from './routes/ib'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as CopyTradingRouteImport } from './routes/copy-trading'
import { Route as CommsRouteImport } from './routes/comms'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const IbRoute = IbRouteImport.update({
  id: '/ib',
  path: '/ib',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTradingRoute = CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsRoute = CommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/commissions': typeof CommissionsRoute
  '/comms': typeof CommsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/financial': typeof FinancialRoute
  '/history': typeof HistoryRoute
  '/ib': typeof IbRoute
  '/kyc': typeof KycRoute
  '/marketing': typeof MarketingRoute
  '/notes': typeof NotesRoute
  '/permissions': typeof PermissionsRoute
  '/referrals': typeof ReferralsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/commissions': typeof CommissionsRoute
  '/comms': typeof CommsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/financial': typeof FinancialRoute
  '/history': typeof HistoryRoute
  '/ib': typeof IbRoute
  '/kyc': typeof KycRoute
  '/marketing': typeof MarketingRoute
  '/notes': typeof NotesRoute
  '/permissions': typeof PermissionsRoute
  '/referrals': typeof ReferralsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/commissions': typeof CommissionsRoute
  '/comms': typeof CommsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/financial': typeof FinancialRoute
  '/history': typeof HistoryRoute
  '/ib': typeof IbRoute
  '/kyc': typeof KycRoute
  '/marketing': typeof MarketingRoute
  '/notes': typeof NotesRoute
  '/permissions': typeof PermissionsRoute
  '/referrals': typeof ReferralsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/commissions'
    | '/comms'
    | '/copy-trading'
    | '/financial'
    | '/history'
    | '/ib'
    | '/kyc'
    | '/marketing'
    | '/notes'
    | '/permissions'
    | '/referrals'
    | '/risk'
    | '/security'
    | '/support'
    | '/trading'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/commissions'
    | '/comms'
    | '/copy-trading'
    | '/financial'
    | '/history'
    | '/ib'
    | '/kyc'
    | '/marketing'
    | '/notes'
    | '/permissions'
    | '/referrals'
    | '/risk'
    | '/security'
    | '/support'
    | '/trading'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/commissions'
    | '/comms'
    | '/copy-trading'
    | '/financial'
    | '/history'
    | '/ib'
    | '/kyc'
    | '/marketing'
    | '/notes'
    | '/permissions'
    | '/referrals'
    | '/risk'
    | '/security'
    | '/support'
    | '/trading'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CommissionsRoute: typeof CommissionsRoute
  CommsRoute: typeof CommsRoute
  CopyTradingRoute: typeof CopyTradingRoute
  FinancialRoute: typeof FinancialRoute
  HistoryRoute: typeof HistoryRoute
  IbRoute: typeof IbRoute
  KycRoute: typeof KycRoute
  MarketingRoute: typeof MarketingRoute
  NotesRoute: typeof NotesRoute
  PermissionsRoute: typeof PermissionsRoute
  ReferralsRoute: typeof ReferralsRoute
  RiskRoute: typeof RiskRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  TradingRoute: typeof TradingRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib': {
      id: '/ib'
      path: '/ib'
      fullPath: '/ib'
      preLoaderRoute: typeof IbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  CommissionsRoute: CommissionsRoute,
  CommsRoute: CommsRoute,
  CopyTradingRoute: CopyTradingRoute,
  FinancialRoute: FinancialRoute,
  HistoryRoute: HistoryRoute,
  IbRoute: IbRoute,
  KycRoute: KycRoute,
  MarketingRoute: MarketingRoute,
  NotesRoute: NotesRoute,
  PermissionsRoute: PermissionsRoute,
  ReferralsRoute: ReferralsRoute,
  RiskRoute: RiskRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  TradingRoute: TradingRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
