/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-trail': typeof AuditTrailRoute
  '/commissions': typeof CommissionsRoute
  '/comms': typeof CommsRoute
  '/copy-trading': typeof CopyTradingRoute
  '/financial': typeof FinancialRoute
  '/history': typeof HistoryRoute
  '/ib': typeof IbRoute
  '/investigate': typeof InvestigateRoute
  '/kyc': typeof KycRoute
  '/marketing': typeof MarketingRoute
  '/notes': typeof NotesRoute
  '/permissions': typeof PermissionsRoute
  '/referrals': typeof ReferralsRoute
  '/risk': typeof RiskRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/audit-trail'
    | '/commissions'
    | '/comms'
    | '/copy-trading'
    | '/financial'
    | '/history'
    | '/ib'
    | '/investigate'
    | '/kyc'
    | '/marketing'
    | '/notes'
    | '/permissions'
    | '/referrals'
    | '/risk'
    | '/security'
    | '/settings'
    | '/support'
    | '/trading'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/audit-trail'
    | '/commissions'
    | '/comms'
    | '/copy-trading'
    | '/financial'
    | '/history'
    | '/ib'
    | '/investigate'
    | '/kyc'
    | '/marketing'
    | '/notes'
    | '/permissions'
    | '/referrals'
    | '/risk'
    | '/security'
    | '/settings'
    | '/support'
    | '/trading'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/audit-trail'
    | '/commissions'
    | '/comms'
    | '/copy-trading'
    | '/financial'
    | '/history'
    | '/ib'
    | '/investigate'
    | '/kyc'
    | '/marketing'
    | '/notes'
    | '/permissions'
    | '/referrals'
    | '/risk'
    | '/security'
    | '/settings'
    | '/support'
    | '/trading'
    | '/wallet'
=======
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
>>>>>>> 6511af4d9019f0a38eacb9d99ae48047dbbfd4a7
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditTrailRoute: typeof AuditTrailRoute
  CommissionsRoute: typeof CommissionsRoute
  CommsRoute: typeof CommsRoute
  CopyTradingRoute: typeof CopyTradingRoute
  FinancialRoute: typeof FinancialRoute
  HistoryRoute: typeof HistoryRoute
  IbRoute: typeof IbRoute
  InvestigateRoute: typeof InvestigateRoute
  KycRoute: typeof KycRoute
  MarketingRoute: typeof MarketingRoute
  NotesRoute: typeof NotesRoute
  PermissionsRoute: typeof PermissionsRoute
  ReferralsRoute: typeof ReferralsRoute
  RiskRoute: typeof RiskRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TradingRoute: typeof TradingRoute
  WalletRoute: typeof WalletRoute
=======
>>>>>>> 6511af4d9019f0a38eacb9d99ae48047dbbfd4a7
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
<<<<<<< HEAD
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib': {
      id: '/ib'
      path: '/ib'
      fullPath: '/ib'
      preLoaderRoute: typeof IbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 6511af4d9019f0a38eacb9d99ae48047dbbfd4a7
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditTrailRoute: AuditTrailRoute,
  CommissionsRoute: CommissionsRoute,
  CommsRoute: CommsRoute,
  CopyTradingRoute: CopyTradingRoute,
  FinancialRoute: FinancialRoute,
  HistoryRoute: HistoryRoute,
  IbRoute: IbRoute,
  InvestigateRoute: InvestigateRoute,
  KycRoute: KycRoute,
  MarketingRoute: MarketingRoute,
  NotesRoute: NotesRoute,
  PermissionsRoute: PermissionsRoute,
  ReferralsRoute: ReferralsRoute,
  RiskRoute: RiskRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TradingRoute: TradingRoute,
  WalletRoute: WalletRoute,
=======
>>>>>>> 6511af4d9019f0a38eacb9d99ae48047dbbfd4a7
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
<<<<<<< HEAD

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
=======
>>>>>>> 6511af4d9019f0a38eacb9d99ae48047dbbfd4a7
